### ISSUE TITLE
handlebars vulnerability

### ISSUE THREAD

**Issue by davityavryan** [ratherblue/hairballs#11]
There is [known vulnerability](https://www.npmjs.com/advisories/755) related to the only dependency that you are using.

Please allow `^4.1.x` or at least upgrade it to `4.0.14` version.

Thanks in advance.

**Comment by ratherblue** [comment]
I'll make that update tonight, thank you for the heads up

**Comment by ratherblue** [comment]
Fixed and 0.3.1 released

**Comment by davityavryan** [comment]
Thanks a lot.
