### ISSUE TITLE
Insecure dependence to handlebars

### ISSUE THREAD

**Issue by pjmolina** [ratherblue/hairballs#6]
Hi:
[Dependences](https://david-dm.org/edendramis/hairballs) shows an insecure dependence to `handlebars 3.0.3`.
Could you please update to `handlebars 4.0.5`?

Security recomendation [#61] (https://nodesecurity.io/advisories/61)

**Comment by ratherblue** [comment]
I'll update the dependencies. But as a side note: the insecurity doesn't affect this project since the html is being rendered into static html as opposed to at run-time, and there is no user-input here so the XSS injection risk doesn't apply. It's still good to be current so I'll update it soon.

**Comment by pjmolina** [comment]
+1 Thanks!

**Comment by ratherblue** [comment]
Updated dependencies today and released version 0.1.0. eslint-html-reporter and scss-lint-html-reporter are also updated with the latest versions.
